import { execFile as execFileCb } from 'node:child_process';
import { promisify } from 'node:util';

const execFile = promisify(execFileCb);

async function run(cmd: string, args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFile(cmd, args, { cwd });
  return stdout.trim();
}

async function isGhInstalled(): Promise<boolean> {
  try {
    await execFile('gh', ['--version']);
    return true;
  } catch {
    return false;
  }
}

export interface PrResult {
  branch: string;
  prUrl: string | null;
}

export async function createArchPr(
  repoRoot: string,
  changedFiles: string[],
  summary: string,
  docsPath?: string,
): Promise<PrResult> {
  const date = new Date().toISOString().split('T')[0];
  const branch = `arch-docs/${date}`;

  try {
    await run('git', ['rev-parse', '--git-dir'], repoRoot);
  } catch {
    throw new Error('Not in a git repository. Cannot create PR.');
  }

  const currentBranch = await run('git', ['branch', '--show-current'], repoRoot);

  try {
    await run('git', ['checkout', '-b', branch], repoRoot);
  } catch {
    await run('git', ['checkout', branch], repoRoot);
  }

  const gitPath = docsPath ?? 'docs/architecture';
  await run('git', ['add', gitPath], repoRoot);

  const commitMsg = `docs: update architecture documentation\n\n${summary}\n\nGenerated by repo-architect`;
  await run('git', ['commit', '-m', commitMsg], repoRoot);

  try {
    await run('git', ['push', '-u', 'origin', branch], repoRoot);
  } catch {
    await run('git', ['checkout', currentBranch], repoRoot);
    return { branch, prUrl: null };
  }

  let prUrl: string | null = null;
  if (await isGhInstalled()) {
    try {
      const prBody = [
        '## Architecture Documentation Update',
        '',
        summary,
        '',
        'Updated files:',
        ...changedFiles.map(f => `- \`${f}\``),
        '',
        '_Generated by [repo-architect](https://github.com/repo-architect/repo-architect)_',
      ].join('\n');

      const result = await run('gh', [
        'pr', 'create',
        '--title', `docs: architecture update ${date}`,
        '--body', prBody,
      ], repoRoot);

      prUrl = result.trim();
    } catch {
      // PR creation failed
    }
  }

  await run('git', ['checkout', currentBranch], repoRoot);

  return { branch, prUrl };
}
